### ISSUE TITLE
マイページ表示・画面のテストを作成する

### ISSUE THREAD

**Issue by inamura0727** [haruka-mitsushima/reserve-system-app#10]
# 概要
マイページ表示・画面のテストを作成する

## 目的
マイページ表示・画面のテストを行うため

## どのページに実装するか
マイページ

## タスク
- [x] 以下の項目にクリアすること
https://docs.google.com/spreadsheets/d/1P6tTO9LSD38unTIUqJz-rWqkLgijSOjyBlbH9dt2beE/edit#gid=1417296324

**Comment by morikimiho** [comment]
勝手にチェックしました〜
